@baseUrl = https://verbose-memory-x5p7gg5pr76g2vrqw-8080.app.github.dev
@contentType = application/json


### Listar todas as categorias
GET {{baseUrl}}/categorias
Accept: {{contentType}}

### Buscar categoria por ID
GET {{baseUrl}}/categorias/1
Accept: {{contentType}}

### Criar nova categoria
POST {{baseUrl}}/categorias
Content-Type: {{contentType}}

{
  "nome": "Programação"
}

### Atualizar categoria
PUT {{baseUrl}}/categorias/1
Content-Type: {{contentType}}

{
  "nome": "Programação Java"
}

### Excluir categoria
DELETE {{baseUrl}}/categorias/1


### ====================== QUESTÕES ======================

### Listar todas as questões
GET {{baseUrl}}/questoes
Accept: {{contentType}}

### Buscar questão por ID
GET {{baseUrl}}/questoes/1
Accept: {{contentType}}

### Criar nova questão
POST {{baseUrl}}/questoes
Content-Type: {{contentType}}

{
  "enunciado": "Qual é a principal característica da programação orientada a objetos?",
  "categoriaId": 1
}

### Atualizar questão
PUT {{baseUrl}}/questoes/1
Content-Type: {{contentType}}

{
  "enunciado": "Explique a principal característica da programação orientada a objetos",
  "categoriaId": 1
}

### Excluir questão
DELETE {{baseUrl}}/questoes/1


### ====================== OPÇÕES ======================

### Listar todas as opções
GET {{baseUrl}}/opcoes
Accept: {{contentType}}

### Buscar opção por ID
GET {{baseUrl}}/opcoes/1
Accept: {{contentType}}

### Criar nova opção
POST {{baseUrl}}/opcoes
Content-Type: {{contentType}}

{
  "descricao": "Encapsulamento",
  "correta": true,
  "questaoId": 1
}

### Criar mais opções para a mesma questão
POST {{baseUrl}}/opcoes
Content-Type: {{contentType}}

{
  "descricao": "Tipagem forte",
  "correta": false,
  "questaoId": 1
}

### Atualizar opção
PUT {{baseUrl}}/opcoes/1
Content-Type: {{contentType}}

{
  "descricao": "Encapsulamento de dados",
  "correta": true,
  "questaoId": 1
}

### Excluir opção
DELETE {{baseUrl}}/opcoes/1
